
<br><br><br><br>

<style>

ul.profile-details{margin-top:10px;padding:0 5px;list-style:none;color:#7c848d}
ul.profile-details li{position:relative;margin:0 0 20px 0;padding-left:22px}

</style>

<div class="col-md-offset-1 row profile">
				
            <div class="col-sm-3">

                    <div class="row">
                            <div class="col-xs-7 col-sm-12">
                                    <img width="100%" class="profile-image" src="/dym/public/images/1e415b4.jpg">
                            </div>
                            <div class="col-xs-5 col-sm-12">                                   	
                                    <h3>Contact Information</h3>

                                    <ul class="profile-details">
                                            <li>
                                                    <div><i class="fa fa-phone"></i> phone</div>
                                                    +48 123 456 789
                                            </li>
                                            <li>
                                                    <div><i class="fa fa-tablet"></i> mobile phone</div>
                                                    +48 123 456 789
                                            </li>
                                            <li>
                                                    <div><i class="fa fa-envelope"></i> e-mail</div>
                                                    msn@dymenstein.com
                                            </li>
                                    </ul>
                            </div>	
                    </div><!--/row-->	

            </div><!--/col-->

            <div class="col-sm-8">

                    <ul class="nav nav-tabs" id="myTab">
                            <li class="active"><a href="page-profile.html#skills">Skills</a></li>
                    </ul>

                    <div class="tab-content">
                            <div class="tab-pane active" id="skills">

                                    <div class="row">

                                            <div class="col-sm-5">
                                                    <h2>Sobre mim</h2>
                                                    <p>Sou engenheiro de software formado na Universidade ORT Uruguai  com especialização em Arquitetura e Desenho de Software.
</p>
                                                    <h2>Bio</h2>
                                                    <p>Trabalhei como desenvolvedor, design e arquiteto de software no  Uruguai, Chile e Brasil; em  pequenos, médios e grandes projetos.
Tenho mais de 10 anos de experiência nas tecnologias de base Java, ASP.NET e PHP.
</p>
                                                    <h2>Job</h2>
                                                    <p>Possuo uma rede de contatos em times de desenvolvimento e gestão de software em vários países e em diferentes línguas.</p>
                                                 <!--   <h2>Languages</h2>
                                                    <div class="row">
                                                            <div class="col-xs-4">
                                                                    <div style="width: 110px; height: 110px; line-height: 110px;" class="language-skill1 easyPieChart" data-percent="90"><span>90</span>%<canvas width="110" height="110"></canvas></div>
                                                <div style="text-align:center">English</div>
                                                            </div><!--/col-->
                                                   <!--         <div class="col-xs-4">
                                                                    <div style="width: 110px; height: 110px; line-height: 110px;" class="language-skill2 easyPieChart" data-percent="43"><span>43</span>%<canvas width="110" height="110"></canvas></div>
                                                <div style="text-align:center">Spanish</div>
                                                            </div>
                                                            <div class="col-xs-4">
                                                                    <div style="width: 110px; height: 110px; line-height: 110px;" class="language-skill3 easyPieChart" data-percent="17"><span>-3150</span>%<canvas width="110" height="110"></canvas></div>
                                                <div style="text-align:center">German</div>
                                                            </div>
                                                    </div>

                                            </div><!--/col-->

                                          <!--  <div class="col-sm-7">
                                                    <h2>My Skills</h2>
                                                    <ul class="skill-bar">
                                                    <li>
                                                    <h5>Web Design</h5>
                                                    <div class="meter"><span class="lightBlue" style="width: 40%;">40%</span></div>
                                                    </li>
                                                    <li>
                                                    <h5>Wordpress</h5>
                                                    <div class="meter"><span class="green" style="width: 80%;">79%</span></div>
                                                    </li>
                                                    <li>
                                                    <h5>Branding</h5>
                                                    <div class="meter"><span class="red" style="width: 100%;">99%</span></div>
                                                    </li>
                                                    <li>
                                                    <h5>SEO Optmization</h5>
                                                    <div class="meter"><span class="lightOrange" style="width: 60%;">59%</span></div>
                                                    </li>

                                            </ul>

                                                    <h2>Other Skills</h2>
                                                    <canvas id="canvas" class="chartjs" height="450" width="450" style="width: 450px; height: 450px;"></canvas>
                                            </div><!--/col-->

                                    </div><!--/row-->		

                            </div>
                          <!--  <div class="tab-pane" id="friends">
                                    <ul class="friends-list clearfix">
                                            <li>
                                                    <a class="avatar" href="page-profile.html#"><img src="assets/img/avatar.jpg"></a>
                                                    <div>Lukasz Holeczek</div>
                                                    <span class="label label-success">active</span>
                                                    <a href="page-profile.html#" class="fa fa-facebook-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-twitter-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-linkedin-square"></a>
                                            </li>
                                            <li>
                                                    <a class="avatar" href="page-profile.html#"><img src="assets/img/avatar2.jpg"></a>
                                                    <div>Ann Polansky</div>
                                                    <span class="label label-warning">busy</span>
                                                    <a href="page-profile.html#" class="fa fa-facebook-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-twitter-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-linkedin-square"></a>
                                            </li>
                                            <li>
                                                    <a class="avatar" href="page-profile.html#"><img src="assets/img/avatar3.jpg"></a>
                                                    <div>May Lin</div>
                                                    <span class="label label-important">blocked</span>
                                                    <a href="page-profile.html#" class="fa fa-facebook-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-twitter-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-linkedin-square"></a>
                                            </li>
                                            <li>
                                                    <a class="avatar" href="page-profile.html#"><img src="assets/img/avatar4.jpg"></a>
                                                    <div>Kate Norman</div>
                                                    <span class="label label-default">offline</span>
                                                    <a href="page-profile.html#" class="fa fa-facebook-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-twitter-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-linkedin-square"></a>
                                            </li>
                                            <li>
                                                    <a class="avatar" href="page-profile.html#"><img src="assets/img/avatar5.jpg"></a>
                                                    <div>Mia Lopez</div>
                                                    <span class="label label-important">blocked</span>
                                                    <a href="page-profile.html#" class="fa fa-facebook-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-twitter-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-linkedin-square"></a>
                                            </li>
                                            <li>
                                                    <a class="avatar" href="page-profile.html#"><img src="assets/img/avatar6.jpg"></a>
                                                    <div>Katia Svoboda</div>
                                                    <span class="label label-success">active</span>
                                                    <a href="page-profile.html#" class="fa fa-facebook-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-twitter-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-linkedin-square"></a>
                                            </li>
                                            <li>
                                                    <a class="avatar" href="page-profile.html#"><img src="assets/img/avatar7.jpg"></a>
                                                    <div>Blanka Rosicky</div>
                                                    <span class="label label-warning">busy</span>
                                                    <a href="page-profile.html#" class="fa fa-facebook-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-twitter-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-linkedin-square"></a>
                                            </li>
                                            <li>
                                                    <a class="avatar" href="page-profile.html#"><img src="assets/img/avatar8.jpg"></a>
                                                    <div>Garry Old</div>
                                                    <span class="label label-success">active</span>
                                                    <a href="page-profile.html#" class="fa fa-facebook-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-twitter-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-linkedin-square"></a>
                                            </li>
                                            <li>
                                                    <a class="avatar" href="page-profile.html#"><img src="assets/img/avatar9.jpg"></a>
                                                    <div>Nick White</div>
                                                    <span class="label label-success">active</span>
                                                    <a href="page-profile.html#" class="fa fa-facebook-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-twitter-square"></a>
                                                    <a href="page-profile.html#" class="fa fa-linkedin-square"></a>
                                            </li>
                                    </ul>	

                            </div>
                            <div class="tab-pane" id="photos">

                                    <div class="row">
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo1.jpg" alt="Sample Image">
                                            </div>
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo2.jpg" alt="Sample Image">
                                            </div>
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo3.jpg" alt="Sample Image">
                                            </div>
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo4.jpg" alt="Sample Image">
                                            </div>
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo5.jpg" alt="Sample Image">
                                            </div>
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo6.jpg" alt="Sample Image">
                                            </div>
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo7.jpg" alt="Sample Image">
                                            </div>
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo8.jpg" alt="Sample Image">
                                            </div>
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo9.jpg" alt="Sample Image">
                                            </div>
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo10.jpg" alt="Sample Image">
                                            </div>
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo11.jpg" alt="Sample Image">
                                            </div>
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo12.jpg" alt="Sample Image">
                                            </div>
                                                                                                            <div style="margin-bottom:30px" class="col-sm-2 col-xs-6">
                                                    <img class="img-thumbnail" src="assets/img/gallery/photo13.jpg" alt="Sample Image">
                                            </div>
                                                                                                    </div>

                            </div>
                    </div>

            </div><!--/col-->	

    </div>

<br><br><br>